### ISSUE TITLE
微前端的模块化问题

### ISSUE THREAD

**Issue by ayiaq1** [CyberFei/puzzle#1]
1.做微前端大多是以发布文件作为加载模块
2.框架应该只做路由层，以及应该考虑一下多模块的切换以及生命周期卸载才能用到大项目上

**Comment by CyberFei** [comment]
这个架构其实是简化版的一个微服务架构，**主要关注的前端模块的聚合及使用webpack去做对应的加载的实现**；而没有去考虑微服务的一些必要特性，如生命周期和技术无关；

框架关注的确实是路由层，以后端的微服务为基础，前端通过不同的用户可以得到不同的元数据（如菜单数据，是否是灰度测试用户，按钮权限之类的），通过这些数据便可以生成路由表并加载对应的模块；而元数据的变化是后端微服务考虑的事情，比如一个统一的用户权限中心等；

以toB的系统为例，此系统可以做到不同业务组的模块全部打包之后，可以简单的通过基座和业务模块的组合产生不同的产品，而系统的加载速度却不会受到影响

**Comment by CyberFei** [comment]
> 1.做微前端大多是以发布文件作为加载模块
> 2.框架应该只做路由层，以及应该考虑一下多模块的切换以及生命周期卸载才能用到大项目上


这个架构其实是简化版的一个微服务架构，主要关注的前端模块的聚合及使用webpack去做对应的加载的实现；而没有去考虑微服务的一些必要特性，如生命周期和技术无关；

框架关注的确实是路由层，以后端的微服务为基础，前端通过不同的用户可以得到不同的元数据（如菜单数据，是否是灰度测试用户，按钮权限之类的），通过这些数据便可以生成路由表并加载对应的模块；而元数据的变化是后端微服务考虑的事情，比如一个统一的用户权限中心等；

以toB的系统为例，此系统可以做到不同业务组的模块全部打包之后，可以简单的通过基座和业务模块的组合产生不同的产品，而系统的加载速度却不会受到影响
