### ISSUE TITLE
实际业务中，共用的 api 接口应该放在哪里

### ISSUE THREAD

**Issue by chakson** [CyberFei/puzzle#10]
比如在 puzzles 业务中，有 database 和 elastic 这两个业务，都调用了同一个 http 请求接口，这时候 api 接口应该写在什么位置，总不能在 database/scripts/api.js 中写一个，在 elastic 中再写一个一样的请求接口。

**Comment by CyberFei** [comment]
首先，子系统的概念应该是蛮大的，子系统之间共用一个接口的情况应该比较少；在我们的实际使用中也是很少遇到；
子系统公用的接口我能想到的一般是一些像获取用户信息这种场景；类似这种情况可以放在基座的 store 的 action 中，子系统通过 this.$store 可以调用
