### ISSUE TITLE
新增模块无法在服务器上加载

### ISSUE THREAD

**Issue by CHENLiver** [CyberFei/puzzle#11]
通过npm run build 命令打包 dashboard以及test，放到服务器后没什么问题，但另外打包database模块后，放到服务器上面， 新增的database模块没有加载出来

**Comment by CyberFei** [comment]
这块应该没有问题，检查下路径
看下对应请求是否能正常请求到模块
![image](https://user-images.githubusercontent.com/31059500/69698998-ce3e3e00-1121-11ea-9539-8177da8eab85.png)

**Comment by CHENLiver** [comment]
打包出来的文件不能带base64吗


&nbsp;



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "CyberFei"<notifications@github.com&gt;; 
发送时间: 2019年11月27日(星期三) 下午2:25
收件人: "CyberFei/puzzle"<puzzle@noreply.github.com&gt;; 
抄送: "陈利伟"<844811632@QQ.COM&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CyberFei/puzzle] 新增模块无法在服务器上加载 (#11)




这块应该没有问题，检查下路径
 看下对应请求是否能正常请求到模块

**Comment by CyberFei** [comment]
我check了一下代码，这边是这样，就是 run build 时会生成一个map文件，用于处理缓存，也就是这个：
![image](https://user-images.githubusercontent.com/31059500/70900992-e32d3380-2034-11ea-8b4e-f0a18e79f4d5.png)

内容是一些模块的 hash
![image](https://user-images.githubusercontent.com/31059500/70901044-fc35e480-2034-11ea-84ee-246e325193ba.png)

如果单独打包模块，这部分可能需要手动维护，不知道你是不是这个原因，可以尝试下
