### ISSUE TITLE
【BUG】Vue Devtools不显示vuex

### ISSUE THREAD

**Issue by Deelout** [CyberFei/puzzle#14]
使用vue devtools开发这工具不能看到store。
已经在入口开启调试工具：
![image](https://user-images.githubusercontent.com/13760972/75506359-be800f80-5a18-11ea-9a25-ac59b8a3f245.png)
调试工具效果如图：
![image](https://user-images.githubusercontent.com/13760972/75506401-dfe0fb80-5a18-11ea-95e8-af1cd879dd06.png)
![image](https://user-images.githubusercontent.com/13760972/75506418-ed968100-5a18-11ea-9a3b-7da148a23d97.png)

**Comment by lyxgy841** [comment]
为什么关闭了，我也遇到了这个问题，请问怎么解决的？

**Comment by cinyearchan** [comment]
执行 `npm run dll` 时，package.json 文件里配置了使用生产模式打包构建 dll，如果要对 vuex 进行调试，需要修改为开发模式构建 dll
