### ISSUE TITLE
【ENHANCENMENT】构建脚手架升级

### ISSUE THREAD

**Issue by Deelout** [CyberFei/puzzle#15]
能否基于vue-cli3或vue-cli4来构建该项目？

**Comment by CyberFei** [comment]
不是，是直接基于webpack做的

**Comment by woyishengwuti** [comment]
> 不是，是直接基于webpack做的

作者您好请问我可以改成vue-cli版本的使用吗

**Comment by CyberFei** [comment]
没试过，简单的通告配置去改估计是不行；可能要写插件或者是引用webpack配置；一般复杂的工程脚手架都是自己写的
