### ISSUE TITLE
生产环境部分导出模块的bug

### ISSUE THREAD

**Issue by ameibj** [CyberFei/puzzle#22]
目前只关注生产环境： 如果build  后 没有选择全部的 puzzle模块内的 子页面，然后 运行后，在单独 发布一个之前未添加的页面 puzzlesDetail 页没有成功加载的

**Comment by CyberFei** [comment]
不是很明白，puzzle是支持生产环境热插拔的，单独发布一个页面是指？

**Comment by ameibj** [comment]
我这里发图比较费劲。刚看到您正好在线，如果方便QQ 交流一下。 576164240

**Comment by CyberFei** [comment]
分布式问题，已解决
