### ISSUE TITLE
请教一下,如果优化开发模式下的启动速度

### ISSUE THREAD

**Issue by zsedcbm** [CyberFei/puzzle#23]
随着项目中页面的增多, 现在每次启动开发模式需要3分钟, 页面上点击一个页面加载的时候也明显变慢, 怎么调整可以减少开发模式中需要加载的模块?

**Comment by CyberFei** [comment]
不太可能吧，页面都是懒加载的啊，你是有多少个页面？

另外模块是根据请求的菜单数据进行加载的，如果想要减少加载的模块，可以修改菜单数据，或者本地的puzzles文件夹里不要放太多的模块。

这个架构本身就是为了让各个模块可以分开开发，做到模块独立开发，灵活组合发布的效果。所以我都没有花太多的心思在开发模式上。

**Comment by zsedcbm** [comment]
因为页面比较复杂, 所以我这边一个页面基本上拆成2,3个vue文件进行开发, 总的模块里面有上千个文件了.
可能是因为模块独立开发了, 但是代码都在一个项目里, 启动的顺序变慢了.

**Comment by CyberFei** [comment]
这么多文件的话，启动慢也是很正常的，应该和架构无关，相关的优化都是通用的，可以网上找下。最简单的方式应该是把puzzle里的模块删除一些。

如果是这么庞大的系统的话，建议你们用模块拆分的方式，所有模块全部放在一个项目里是不太合适的，应该按模块划分，每一个或者每几个模块单独维护；这也是我前面说的那种方式：模块独立开发，灵活组合发布，不过这块可能需要你们在工程化上做一些努力，比如使用jenkins集成发布等

**Comment by zsedcbm** [comment]
看样子我的问题已经超出这个项目的范畴了, 关于独立开发能否再详细讲解一下? 框架和公共代码组件需要复制一份新的在新模块项目中进行开发吗?这样维护的时候好像有点麻烦.

**Comment by CyberFei** [comment]
是的，工程化的话，可能需要配套的一些项目，比如脚手架工具：用来生成项目，更新框架等；私有npm：用来维护公共组件；

**Comment by CyberFei** [comment]
项目做大之后，肯定是要有相应的基础设施来支持了

**Comment by zsedcbm** [comment]
谢谢, 工程化的话, 还得多研究研究.
