### ISSUE TITLE
你好作者，问一下，为什么test 模块不能被更新呢

### ISSUE THREAD

**Issue by 15738039217** [CyberFei/puzzle#25]
我在test 里面的vue文件修改了文字，预览或更新的时候发现页面没有被更新，其他页面没有这种情况， 看到了test 有个模块名字为测试页面 KeepAlive ，请问一下在哪里设置页面被更新不被缓存呢

**Comment by 15738039217** [comment]
基座代码index keep 已经注释了
   <div id="con" class="full">
      
        
      
      <router-view/>

    </div>

**Comment by 15738039217** [comment]
<div id="con" class="full">
      
        
      
      <router-view/>
    </div>

**Comment by 15738039217** [comment]
<keep-alive></keep-alive> 注释了，

**Comment by CyberFei** [comment]
![image](https://user-images.githubusercontent.com/31059500/96829180-a491b200-146b-11eb-9e55-85798da39984.png)
test 模块是远程分布式加载的，你可以把分布式相关的参数注释掉；https://github.com/CyberFei/puzzle/blob/master/update_log.md

 KeepAlive 的机制是打开的tab都被 KeepAlive ，这块的逻辑，你可以自己修改一下，加参数或者配置什么；关键代码在这：
![image](https://user-images.githubusercontent.com/31059500/96829294-ede20180-146b-11eb-950b-5b52fd49a24e.png)

**Comment by 15738039217** [comment]
你好，缓存的问题解决了，但是在基座中 路由进行跳转的时候发现控制台有一个报错信息，TypeError: Cannot read property '__ob__' of undefined，错误文件来源为core.js, 操作流程，是油home 页跳转到login单独页面，然后由login 返回home页时控制器输出的错误，但似乎不影响程序进程， 具体错误：
core.f5dcb2c61d39e134ede4.dll.js:7 TypeError: Cannot read property '__ob__' of undefined
    at a.t.$destroy (core.f5dcb2c61d39e134ede4.dll.js:7)
    at destroy (core.f5dcb2c61d39e134ede4.dll.js:7)
    at _ (core.f5dcb2c61d39e134ede4.dll.js:7)
    at w (core.f5dcb2c61d39e134ede4.dll.js:7)
    at a.__patch__ (core.f5dcb2c61d39e134ede4.dll.js:7)
    at a.t._update (core.f5dcb2c61d39e134ede4.dll.js:7)
    at a.r (core.f5dcb2c61d39e134ede4.dll.js:7)
    at vn.get (core.f5dcb2c61d39e134ede4.dll.js:7)
    at vn.run (core.f5dcb2c61d39e134ede4.dll.js:7)
    at dn (core.f5dcb2c61d39e134ede4.dll.js:7)
Kt @ core.f5dcb2c61d39e134ede4.dll.js:7
zt @ core.f5dcb2c61d39e134ede4.dll.js:7
qt @ core.f5dcb2c61d39e134ede4.dll.js:7
(anonymous) @ core.f5dcb2c61d39e134ede4.dll.js:7
Zt @ core.f5dcb2c61d39e134ede4.dll.js:7
Promise.then (async)
Jt @ core.f5dcb2c61d39e134ede4.dll.js:7
ne @ core.f5dcb2c61d39e134ede4.dll.js:7
(anonymous) @ core.f5dcb2c61d39e134ede4.dll.js:7
vn.update @ core.f5dcb2c61d39e134ede4.dll.js:7
pt.notify @ core.f5dcb2c61d39e134ede4.dll.js:7
set @ core.f5dcb2c61d39e134ede4.dll.js:7
(anonymous) @ core.f5dcb2c61d39e134ede4.dll.js:7
(anonymous) @ core.f5dcb2c61d39e134ede4.dll.js:7
_t.updateRoute @ core.f5dcb2c61d39e134ede4.dll.js:7
(anonymous) @ core.f5dcb2c61d39e134ede4.dll.js:7
(anonymous) @ core.f5dcb2c61d39e134ede4.dll.js:7
r @ core.f5dcb2c61d39e134ede4.dll.js:7
r @ core.f5dcb2c61d39e134ede4.dll.js:7
r @ core.f5dcb2c61d39e134ede4.dll.js:7
ht @ core.f5dcb2c61d39e134ede4.dll.js:7
(anonymous) @ core.f5dcb2c61d39e134ede4.dll.js:7
r @ core.f5dcb2c61d39e134ede4.dll.js:7
(anonymous) @ core.f5dcb2c61d39e134ede4.dll.js:7
(anonymous) @ core.f5dcb2c61d39e134ede4.dll.js:7
(anonymous) @ core.f5dcb2c61d39e134ede4.dll.js:7
(anonymous) @ core.f5dcb2c61d39e134ede4.dll.js:7
Promise.then (async)
(anonymous) @ core.f5dcb2c61d39e134ede4.dll.js:7
(anonymous) @ core.f5dcb2c61d39e134ede4.dll.js:7
(anonymous) @ core.f5dcb2c61d39e134ede4.dll.js:7
mt @ core.f5dcb2c61d39e134ede4.dll.js:7
(anonymous) @ core.f5dcb2c61d39e134ede4.dll.js:7
p @ core.f5dcb2c61d39e134ede4.dll.js:7
r @ core.f5dcb2c61d39e134ede4.dll.js:7
r @ core.f5dcb2c61d39e134ede4.dll.js:7
r @ core.f5dcb2c61d39e134ede4.dll.js:7
(anonymous) @ core.f5dcb2c61d39e134ede4.dll.js:7
(anonymous) @ core.f5dcb2c61d39e134ede4.dll.js:7
(anonymous) @ router.js:39
p @ core.f5dcb2c61d39e134ede4.dll.js:7
r @ core.f5dcb2c61d39e134ede4.dll.js:7
r @ core.f5dcb2c61d39e134ede4.dll.js:7
ht @ core.f5dcb2c61d39e134ede4.dll.js:7
_t.confirmTransition @ core.f5dcb2c61d39e134ede4.dll.js:7
_t.transitionTo @ core.f5dcb2c61d39e134ede4.dll.js:7
e.push @ core.f5dcb2c61d39e134ede4.dll.js:7
Rt.push @ core.f5dcb2c61d39e134ede4.dll.js:7
login @ Login.vue:18
click @ Login.vue?d08f:35
Vt @ core.f5dcb2c61d39e134ede4.dll.js:7
n @ core.f5dcb2c61d39e134ede4.dll.js:7
Vt @ core.f5dcb2c61d39e134ede4.dll.js:7
t.$emit @ core.f5dcb2c61d39e134ede4.dll.js:7
handleClick @ element-ui.common.js:9417
Vt @ core.f5dcb2c61d39e134ede4.dll.js:7
n @ core.f5dcb2c61d39e134ede4.dll.js:7
i._wrapper @ core.f5dcb2c61d39e134ede4.dll.js:7

**Comment by CyberFei** [comment]
这个一时就不知道了，可能哪里的语法不符合规范吧，我这边是没有错误的

**Comment by 15738039217** [comment]
好的，项目可以改变路由方式嘛，可以修改成history模式嘛

**Comment by CyberFei** [comment]
应该可以的，这个和项目无关，按照官方文档改就行

**Comment by 15738039217** [comment]
作者能建一个交流群嘛，设置 路由 mode: "history",  base: "/vue/",  时，本地编译时，路由一切正常，但是一刷新，页面就失去链接了 Cannot GET /home 变成这样的页面home:1 GET http://localhost:8080/home 404 (Not Found)，仅限刷新的情况下，运行时切换路由没问题，

**Comment by CyberFei** [comment]
你后端做了对history的支持吗？

**Comment by 15738039217** [comment]
这是我本地的项目，暂时没有部署到后端服务器上呢，，从作者项目下载下来.然后修改了 mode: "history",
  base: "__dirname",  然后进行项目 npm start ,项目正常运行，点击侧栏导航路由跳转正常，但是一刷新，则断开项目，或者从浏览器地址栏复制到另一个浏览器时也是不被加载，

**Comment by CyberFei** [comment]
history模式是需要后端支持的，我建议你看下官方的文档
https://router.vuejs.org/zh/guide/essentials/history-mode.html

**Comment by CyberFei** [comment]
history 模式我接触也比较少，但是我这个项目应该没有涉及到这部分，路由是按照官方的方式生成的；
所以这块理论上应该没问题，你可以再看看，我这边有空的话也去测试一下

**Comment by 15738039217** [comment]
嗯嗯，谢谢
