### ISSUE TITLE
关于配置项的问题

### ISSUE THREAD

**Issue by zsedcbm** [CyberFei/puzzle#3]
我原先是写了一个dev.env.js 和 prod.env.js 的系统环境变量文件, 用于区分开发环境和生产环境的变量,
然后在webpack的plugins中添加
```
    new webpack.DefinePlugin({
      'process.env': require('./dev.env')
    }),
```
项目中通过 process.env.XXX 来获取配置的变量.

现在我在 webpack.build.common.js 中增加了这个配置, 为什么读取不到这个变量?

我应该怎么改?

**Comment by CyberFei** [comment]
webpack.build.common.js是用于打包的，你可以尝试修改webpack.common.js

**Comment by zsedcbm** [comment]
加载webpack.common.js 中有效, 但是我不知道怎么在此处进行区分开发模式和生产模式.

最后我在webpack.dev.js 中添加了开发模式的配置, 在webpack.build.core.js中添加了生产模式的配置后有效.

**Comment by CyberFei** [comment]
> 加载webpack.common.js 中有效, 但是我不知道怎么在此处进行区分开发模式和生产模式.
> 
> 最后我在webpack.dev.js 中添加了开发模式的配置, 在webpack.build.core.js中添加了生产模式的配置后有效.

主要是为了实现生产环境下的可插拔，所以区分不同的打包方式
