### ISSUE TITLE
请问如何解决缓存问题

### ISSUE THREAD

**Issue by HuangZhaoPing** [CyberFei/puzzle#4]
生成的文件都是不带hash的，修改后需要清除缓存才能正常显示

**Comment by HuangZhaoPing** [comment]
已解决，

**Comment by CyberFei** [comment]
> 已解决，

抱歉，我没看到第一封邮件，现在架构里面确实没有处理缓存的问题；
如果你有时间，可以把解决的方法写在这里，方便其他人遇到同样的问题可以参考，或者提一个PR完善这个架构

**Comment by HuangZhaoPing** [comment]
> > 已解决，
> 
> 抱歉，我没看到第一封邮件，现在架构里面确实没有处理缓存的问题；
> 如果你有时间，可以把解决的方法写在这里，方便其他人遇到同样的问题可以参考，或者提一个PR完善这个架构

我们的项目架构和您的有点不一样，是以一级菜单作为子项目，整个项目未来大概会有9个子项目左右，我的解决方案比较暴力，将项目的udm模块分成了vendors（外部依赖，vue，vue-router……）、app（全局组件、utils、mixin……）和各个子项目，webpack配置文件直接添加 [name].[hash]，所有项目打包完后，再执行一个方法，将dist下所有目录的入口文件名读取出来（我们项目规定为main.*.js），然后生成一个对象 如 window.xxx = { xxx: 'main.12adfa.js' }，这样loadjs读取文件时就可以拿到文件名了，最后将这个对象写入js文件并用md5生成hash输出 到dist目录下，然后通过html-webpack-tags-plugin将config.*.js、vendors.*.js、app.*.js注入到index.html中

**Comment by CyberFei** [comment]
> > > 已解决，
> > 
> > 
> > 抱歉，我没看到第一封邮件，现在架构里面确实没有处理缓存的问题；
> > 如果你有时间，可以把解决的方法写在这里，方便其他人遇到同样的问题可以参考，或者提一个PR完善这个架构
> 
> 我们的项目架构和您的有点不一样，是以一级菜单作为子项目，整个项目未来大概会有9个子项目左右，我的解决方案比较暴力，将项目的udm模块分成了vendors（外部依赖，vue，vue-router……）、app（全局组件、utils、mixin……）和各个子项目，webpack配置文件直接添加 [name].[hash]，所有项目打包完后，再执行一个方法，将dist下所有目录的入口文件名读取出来（我们项目规定为main.*.js），然后生成一个对象 如 window.xxx = { xxx: 'main.12adfa.js' }，这样loadjs读取文件时就可以拿到文件名了，最后将这个对象写入js文件并用md5生成hash输出 到dist目录下，然后通过html-webpack-tags-plugin将config.*.js、vendors.*.js、app.*.js注入到index.html中

好的，了解了

**Comment by CyberFei** [comment]
> 生成的文件都是不带hash的，修改后需要清除缓存才能正常显示

缓存的问题，我已经完善了
