### ISSUE TITLE
请问如何支持 history 路由

### ISSUE THREAD

**Issue by chakson** [CyberFei/puzzle#6]
已有的项目想结合这种热插拔，但是 vue-router 是用的 history 模式。我测试过这个 puzzle-demo 如果用 history 模式，会报错，请问能支持 history 路由吗？

**Comment by CyberFei** [comment]
> 已有的项目想结合这种热插拔，但是 vue-router 是用的 history 模式。我测试过这个 puzzle-demo 如果用 history 模式，会报错，请问能支持 history 路由吗？

刚才我抽时间测试了一下，是支持的，只不过使用 history 时，你需要配置路由的 base 字段，比如你的访问地址为 127.0.0.1:8080/demo ，那么你的路由base需要配置为 "/demo"

**Comment by chakson** [comment]
开发模式下，的确是可以。
但是在生成环境下不行，页面不能访问。

我的路由配置如下：
![image](https://user-images.githubusercontent.com/13362753/63069139-5e2bf380-bf48-11e9-87be-b77db762597f.png)

生成环境下，打包出来 dist 文件后，再用 node 启动服务，监听 500 端口，报错如下：
![image](https://user-images.githubusercontent.com/13362753/63069163-7bf95880-bf48-11e9-935b-fecd8b1c737b.png)

**Comment by CyberFei** [comment]
> 开发模式下，的确是可以。
> 但是在生产环境下不行，页面不能访问。
> 
> 我的路由配置如下：
> ![image](https://user-images.githubusercontent.com/13362753/63069139-5e2bf380-bf48-11e9-87be-b77db762597f.png)
> 
> 生产环境下，打包出来 dist 文件后，再用 node 启动服务，监听 500 端口，报错如下：
> ![image](https://user-images.githubusercontent.com/13362753/63069163-7bf95880-bf48-11e9-935b-fecd8b1c737b.png)

昨天我疏忽了，不仅要配置路由的 base ，还需要把 webpack 打包的 publicPath 配置成绝对路径
![image](https://user-images.githubusercontent.com/31059500/63082619-43be3e00-bf79-11e9-8ccc-db9e5720172d.png)
如上图所示的前两个配置

**Comment by chakson** [comment]
> > 开发模式下，的确是可以。
> > 但是在生产环境下不行，页面不能访问。
> > 我的路由配置如下：
> > ![image](https://user-images.githubusercontent.com/13362753/63069139-5e2bf380-bf48-11e9-87be-b77db762597f.png)
> > 生产环境下，打包出来 dist 文件后，再用 node 启动服务，监听 500 端口，报错如下：
> > ![image](https://user-images.githubusercontent.com/13362753/63069163-7bf95880-bf48-11e9-935b-fecd8b1c737b.png)
> 
> 昨天我疏忽了，不仅要配置路由的 base ，还需要把 webpack 打包的 publicPath 配置成绝对路径
> ![image](https://user-images.githubusercontent.com/31059500/63082619-43be3e00-bf79-11e9-8ccc-db9e5720172d.png)
> 如上图所示的前两个配置

---------------------------------------------------------------------------------
我按你那样配置不行，页面加载不出来：
![image](https://user-images.githubusercontent.com/13362753/63084540-fbede580-bf7d-11e9-8afb-9629e95f36c5.png)

但是我将配置路由的 base 注释掉；再将 publicPath 配置成绝对路径（绝对路径的点去掉），如下图之后，这样是可以的，这个是为什么？
![image](https://user-images.githubusercontent.com/13362753/63084405-a6193d80-bf7d-11e9-8460-18e83ba963dd.png)

![image](https://user-images.githubusercontent.com/13362753/63084382-9ac61200-bf7d-11e9-906b-019f658c8a0d.png)

**Comment by CyberFei** [comment]
不是，你理解错了，base 和 publicPath 保持一致就可以了；
比如你的 base 配置 /demo
publicPath 就要以 /demo/xxxx 这样的形式
然后访问地址就是 127.0.0.1:8080/demo/ 这样

你不配置base，默认是 "/"
刚好与下面的 publicPath 的 /xxxx 对应
所以你的访问地址就是 127.0.0.1:8080/ 也是可以

![image](https://user-images.githubusercontent.com/31059500/63085049-25f3d780-bf7f-11e9-9062-9d9a5f335fac.png)

**Comment by chakson** [comment]
但是我 base 和 publicPath 同时加了 /demo ，无法加载页面，报下面这个错，不加就可以
![image](https://user-images.githubusercontent.com/13362753/63085602-7881c380-bf80-11e9-9674-8d55a0d902b6.png)

**Comment by CyberFei** [comment]
我感觉这个应该是你的 nginx 服务器配置问题了，相关的配置我在本地已经测试过了，是可以的哦；

刚看你的截图是不是路径有点问题，如果你配置了 /demo ，你的路径应该是 localhost:500/demo/ 才对吧；
你这个错误应该是找不到文件，nginx 重定向返回一个 HTML ，导致无法解析；具体你可以看下请求的返回

**Comment by chakson** [comment]
好，我再研究一下，谢谢你啦！

**Comment by CyberFei** [comment]
> 好，我再研究一下，谢谢你啦！

没关系，大家共同进步啦

**Comment by 15738039217** [comment]
为什么我 改成 mode: "history" 时 本地编译后 页面成功加载，但是一刷新 页面就报错了，直接显示 Cannot GET /vue/elastic/ecs 这样了，不管项目怎么刷新都是这样，必须重新启动才能成功加载

**Comment by 15738039217** [comment]
mode: "history",
    base: "/vue",

**Comment by 15738039217** [comment]
我再切换到mode: "hash", 刷新就没问题
