### ISSUE TITLE
关于构建第三方依赖报错问题

### ISSUE THREAD

**Issue by Xiao-HuangShu** [CyberFei/puzzle#8]
![image](https://user-images.githubusercontent.com/27752523/64499147-66c6de00-d2ea-11e9-8716-b8fc94e74c96.png)
webpack.build.dll.js配置文件入口 puzzle: []不能为空数组，这是什么原因

**Comment by CyberFei** [comment]
好的，我抽空验证一下

**Comment by Xiao-HuangShu** [comment]
![image](https://user-images.githubusercontent.com/27752523/64499545-181a4380-d2ec-11e9-8cdd-448ed4b610ce.png)
这个是抛出的错误

**Comment by Xiao-HuangShu** [comment]
这个事dev分支下的问题，master分支并不存在

**Comment by CyberFei** [comment]
其实问题应该都是存在的，只不过master现在那个puzzle不是空数组，所以问题没有出现，这块我抽空会解决的
