### ISSUE TITLE
子模块是否可以独立部署

### ISSUE THREAD

**Issue by Xiao-HuangShu** [CyberFei/puzzle#9]
最近才接触微前端的概念，冒昧问一下作者大大，我有看到您项目介绍里说用您的框架开发的子项目打包后可以快速组合，是不是意味着用其它框架打包的项目无法组合，子项目也无法做到独立部署

**Comment by CyberFei** [comment]
是的，你这种设计的微服务的范畴了；想做技术无关的话，需要更庞杂的系统和设计，我这块就没有涉及了；你可以参考一些更加偏向典型微服务的设计，比如https://github.com/CanopyTax/single-spa

**Comment by Xiao-HuangShu** [comment]
好的，谢谢
